In [1]:
import numpy as np 

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
 arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_off_arr = arr[:6]

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[2,1]

40

In [40]:
arr_2d_copy = arr_2d[:2,1:].copy()

In [41]:
arr_2d_copy

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d_copy[:] = 1

In [43]:
arr_2d_copy

array([[1, 1],
       [1, 1]])

In [44]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [48]:
bool_arr = arr > 5

In [49]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [50]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [61]:
3 * arr 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [62]:
arr/arr

/tmp/ipykernel_21252/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [63]:
1/arr

/tmp/ipykernel_21252/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [64]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])